/* Fenhao Special 20260922-special1. All playback dependencies are same-origin. */
(() => {
'use strict';
const VERSION='20260922-special1', $=s=>document.querySelector(s), make=(t,c,text)=>{const n=document.createElement(t);if(c)n.className=c;if(text!==undefined)n.textContent=text;return n;};
const assets=(window.SPECIAL_ASSETS?.items||[]).map(a=>({...a,kind:'sticker'}));
const styles=[['comic','漫画爆炸牌','选项弹出来，态度亮出来'],['jelly','弹力软糖牌','轻轻一弹，答案很醒目'],['sign','小人举牌','四个选项，一眼就看清']];
const answers=styles.flatMap(([style,title,caption])=>'ABCD'.split('').map(letter=>({id:`answer-${style}-${letter}`,kind:'answer',group:style,letter,name:`${title} ${letter}`,caption:`我选 ${letter}`,format:'Lottie JSON / Animated WebP',license:'本页原创矢量动画 · MIT',source:location.href,styleTitle:title})));
const effects=[
{id:'fx-cannon',name:'双侧礼炮',caption:'两侧喷射，彩纸在画面中汇合',word:'答得漂亮！',key:'cannon',engine:'canvas-confetti',glyph:'POP!'},
{id:'fx-fireworks',name:'烟花大秀',caption:'真实粒子拖尾、升空、爆炸',word:'把掌声送给你',key:'fireworks',engine:'fireworks-js',glyph:'BOOM'},
{id:'fx-gold',name:'金色加冕',caption:'金片缓落，适合表扬与结课',word:'今日高光时刻',key:'gold',engine:'canvas-confetti',glyph:'MVP'},
{id:'fx-heart',name:'爱心爆破',caption:'心形粒子向外绽放，不只是飘 emoji',word:'老师辛苦了',key:'heart',engine:'canvas-confetti',glyph:'LOVE'},
{id:'fx-stars',name:'星星喷泉',caption:'金色五角星弹射，像通关奖励',word:'这个知识点，拿下',key:'stars',engine:'canvas-confetti',glyph:'NICE'},
{id:'fx-warp',name:'冲刺穿梭',caption:'星轨向外拉伸，制造起飞感',word:'冲上岸！',key:'warp',engine:'原创 Canvas 编排',glyph:'GO!'},
{id:'fx-shock',name:'答案暴击',caption:'冲击圆环与聚光，不频闪',word:'原来如此！',key:'shock',engine:'原创 Canvas 编排',glyph:'懂了'},
{id:'fx-parade',name:'小鸟巡游',caption:'搞怪角色横穿屏幕，庆祝下课',word:'下课啦！',key:'parade',engine:'Party Parrot + canvas-confetti',glyph:'PARTY'}
].map(a=>({...a,kind:'effect',format:'网页全屏特效',license:a.key==='parade'?'引擎 MIT；角色许可另核':'MIT',source:a.engine.includes('fireworks')?'https://github.com/crashmax-dev/fireworks-js':'https://github.com/catdad/canvas-confetti'}));
const catalog=[...assets,...answers,...effects], byId=new Map(catalog.map(a=>[a.id,a]));
let tab='stickers',filter='all',mode='chat',messages=0,favorites=new Set(),galleryAnims=[],chatAnims=[],detailAnims=[],fxCleanup=null,fxTimer=0,storageWarned=false;
try{const saved=JSON.parse(localStorage.getItem('fenhao-special-favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved.filter(id=>byId.has(id)));}catch(_){}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2300);}
function save(){try{localStorage.setItem('fenhao-special-favorites',JSON.stringify([...favorites]));}catch(_){if(!storageWarned){toast('当前浏览器不能保存收藏，请导出清单');storageWarned=true;}}$('#favCount').textContent=favorites.size;}
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}));const a=make('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
// Standalone vector Lottie animations for answer buttons. No font assets required.
const color=h=>[parseInt(h.slice(1,3),16)/255,parseInt(h.slice(3,5),16)/255,parseInt(h.slice(5,7),16)/255,1];
const ink='#24283f', colors=['#dafa83','#ffb194','#aacaef','#cbb3fa'];
const prop=k=>({a:0,k});
const key=(t,s)=>({t,s:Array.isArray(s)?s:[s],i:{x:[.65],y:[1]},o:{x:[.3],y:[0]}});
function line(v,closed=false){return{ty:'sh',ks:prop({v,i:v.map(()=>[0,0]),o:v.map(()=>[0,0]),c:closed})};}
function paint(shape,fill,stroke=ink,width=5){const it=[shape];if(fill)it.push({ty:'fl',c:prop(color(fill)),o:prop(100),r:1});if(stroke)it.push({ty:'st',c:prop(color(stroke)),o:prop(100),w:prop(width),lc:2,lj:2});it.push({ty:'tr',p:prop([0,0]),a:prop([0,0]),s:prop([100,100]),r:prop(0),o:prop(100)});return{ty:'gr',it};}
function ellipse(x,y,w,h,fill,stroke=ink,sw=5){return paint({ty:'el',p:prop([x,y]),s:prop([w,h])},fill,stroke,sw);}
function rect(x,y,w,h,r,fill,stroke=ink,sw=5){return paint({ty:'rc',p:prop([x,y]),s:prop([w,h]),r:prop(r)},fill,stroke,sw);}
function glyph(letter,cx,cy,scale=1){const paths={A:[[[90,164],[128,80],[166,164]],[[104,136],[151,136]]],B:[[[94,164],[94,80],[135,80],[155,87],[159,101],[151,116],[134,122],[94,122]],[[134,122],[157,130],[161,145],[151,159],[135,164],[94,164]]],C:[[[166,94],[151,83],[130,79],[109,87],[96,103],[91,123],[97,144],[112,160],[134,165],[154,159],[166,150]]],D:[[[95,80],[95,164],[130,164],[151,153],[164,132],[164,112],[152,91],[131,80],[95,80]]]};return paths[letter].map(p=>paint(line(p.map(([x,y])=>[(x-128)*scale+cx,(y-123)*scale+cy])),null,ink,14*scale));}
function lottieFor(a){const idx='ABCD'.indexOf(a.letter),fill=colors[idx];let shapes=[];if(a.group==='comic'){
 const points=Array.from({length:24},(_,i)=>{const r=i%2?77:107,ang=-Math.PI/2+i*Math.PI/12;return[128+Math.cos(ang)*r,128+Math.sin(ang)*r]});
 shapes=[...glyph(a.letter,128,122),paint(line(points,true),fill)];
}else if(a.group==='jelly'){
 shapes=[...glyph(a.letter,128,124,.9),ellipse(100,198,9,9,ink,null),ellipse(155,198,9,9,ink,null),rect(128,122,174,182,43,fill),rect(134,130,174,182,43,ink,ink)];
}else{
 shapes=[...glyph(a.letter,128,93,.72),ellipse(103,185,7,9,ink,null),ellipse(149,185,7,9,ink,null),paint(line([[116,201],[128,206],[139,200]]),null,ink,4),ellipse(68,130,24,25,'#fff3d8'),ellipse(188,130,24,25,'#fff3d8'),rect(128,92,136,122,15,fill),ellipse(128,188,92,79,'#fff3d8'),paint(line([[101,223],[87,239]]),null,ink,8),paint(line([[153,223],[166,239]]),null,ink,8)];
}
const scale=a.group==='jelly'?{a:1,k:[key(0,[100,100,100]),key(10,[111,86,100]),key(19,[92,111,100]),key(30,[102,98,100]),key(42,[100,100,100]),key(60,[100,100,100])]}:{a:1,k:[key(0,[96,96,100]),key(10,[108,108,100]),key(23,[98,98,100]),key(35,[100,100,100]),key(60,[96,96,100])]};
return{v:'5.7.4',fr:30,ip:0,op:60,w:256,h:256,nm:`Fenhao ${a.group} ${a.letter}`,ddd:0,assets:[],layers:[{ddd:0,ind:1,ty:4,nm:'answer',sr:1,ks:{o:prop(100),r:{a:1,k:[key(0,-4),key(14,5),key(30,-1),key(44,2),key(60,-4)]},p:prop([128,128,0]),a:prop([128,128,0]),s:scale},ao:0,shapes,ip:0,op:60,st:0,bm:0}]};}
function playLottie(node,a,list){if(!window.lottie){node.append(make('div','load-error','Lottie 播放器未载入'));return;}const anim=lottie.loadAnimation({container:node,renderer:'svg',loop:true,autoplay:!matchMedia('(prefers-reduced-motion: reduce)').matches,animationData:lottieFor(a),rendererSettings:{progressiveLoad:false}});list.push(anim);anim.addEventListener('data_failed',()=>{node.replaceChildren(make('span','load-error','动画解析失败'));});}
function image(a,cls=''){const img=make('img',cls);img.src=a.src;img.alt=a.name;img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>{const p=img.parentElement;if(p){img.hidden=true;p.append(make('span','load-error','动图未加载 · 点详情重试'));}},{once:true});return img;}
function thumb(a){const box=make('div',`fx-thumb ${a.key}`);const cs=['#b6a0ff','#dafa83','#ffb194','#aacaef','#ffd486'];for(let i=0;i<25;i++){const p=make('span');p.style.setProperty('--x',((i*71)%100)+'%');p.style.setProperty('--y',((i*37)%100)+'%');p.style.setProperty('--angle',(i*37)+'deg');p.style.setProperty('--color',cs[i%5]);box.append(p);}box.append(make('strong','',a.glyph));if(a.key==='parade'&&assets.find(x=>x.id==='parrot-0')){for(let i=0;i<3;i++){const im=image(byId.get('parrot-0'));im.src=byId.get('parrot-0').poster;im.style.left=(10+i*28)+'%';box.append(im);}}return box;}
function art(a,animList=galleryAnims){const box=make('div','art');if(a.kind==='sticker'){box.append(image(a));box.append(make('span','size',Math.round(a.bytes/1024)+' KB'));}else if(a.kind==='answer'){const el=make('div','answer-art');box.append(el);queueMicrotask(()=>playLottie(el,a,animList));}else box.append(thumb(a));return box;}
function tile(a){const el=make('article','tile'),button=make('button','send');button.dataset.send=a.id;button.setAttribute('aria-label','发送 '+a.name);button.append(art(a),make('div','tile-name',a.name),make('div','tile-caption',a.caption));button.onclick=()=>send(a);const actions=make('div','tile-actions');const fav=make('button',favorites.has(a.id)?'selected':'',favorites.has(a.id)?'♥ 已收藏':'♡ 收藏');fav.dataset.fav=a.id;fav.onclick=()=>{favorites.has(a.id)?favorites.delete(a.id):favorites.add(a.id);save();fav.textContent=favorites.has(a.id)?'♥ 已收藏':'♡ 收藏';fav.classList.toggle('selected',favorites.has(a.id));if(tab==='favorites')render();};const info=make('button','','详情 ↗');info.dataset.info=a.id;info.onclick=()=>showDetail(a);actions.append(fav,info);el.append(button,actions);return el;}
function dispose(list){for(const a of list)a.destroy();list.length=0;}
function render(){dispose(galleryAnims);const options=tab==='stickers'?[['all','全部 20'],['fluent','立体夸张 12'],['parrot','鬼畜小鸟 8']]:tab==='answers'?[['all','三套全部'],...styles.map(s=>[s[0],s[1]])]:[];$('#filters').replaceChildren(...options.map(([id,title])=>{const b=make('button',filter===id?'on':'',title);b.onclick=()=>{filter=id;render();};return b;}));const titles={stickers:['夸张一点，才有记忆点。','点大图发聊天，点详情放大看。'],effects:['不只是飘几个小图标。','礼炮、烟花、穿梭、巡游，八种不同的出场方式。'],answers:['A 就是 A，B 就是 B。','三个完整系列，各含 ABCD；大字母与动态造型一起发。'],favorites:['把喜欢的留下。','导出后交给开发，附带来源、文件地址和效果配置。']};$('#sectionTitle').textContent=titles[tab][0];$('#sectionDesc').textContent=titles[tab][1];let list=tab==='stickers'?assets:tab==='answers'?answers:tab==='effects'?effects:catalog.filter(a=>favorites.has(a.id));if(filter!=='all'&&['stickers','answers'].includes(tab))list=list.filter(a=>a.group===filter);const g=$('#gallery');g.className='gallery '+(tab==='effects'?'effects-gallery':tab==='answers'?'answers-gallery':'');g.replaceChildren(...list.map(tile));if(!list.length)g.append(make('p','empty',tab==='favorites'?'还没有收藏。试玩后，喜欢哪个再点心形按钮。':'素材未成功载入，请刷新本页。'));}
function send(a){const row=make('div','message'),avatar=make('span','','我'),bubble=make('div');if(a.kind==='sticker')bubble.append(image(a,'chat-sticker'));else if(a.kind==='answer'){const el=make('div','answer-art');bubble.append(el);queueMicrotask(()=>playLottie(el,a,chatAnims));}else bubble.append(make('div','','✦ 全屏互动'));bubble.append(make('b','',a.kind==='answer'?a.caption:a.name));const replay=make('button','replay','再播一次 ↻');replay.onclick=()=>a.kind==='effect'?playEffect(a):playHero(a);bubble.append(replay);row.append(avatar,bubble);$('#chat').append(row);messages++;$('#messageCount').textContent=messages;$('#chat').scrollTop=$('#chat').scrollHeight;if(a.kind==='effect')playEffect(a);else if(mode==='both')playHero(a);else{toast('已发送「'+(a.kind==='answer'?a.caption:a.name)+'」');if(innerWidth<=780)document.body.classList.add('chat-open');}if(messages>30){const first=$('#chat .message:not(.sys)');if(first)first.remove();if(chatAnims.length>24)chatAnims.shift().destroy();}}
function stop(){clearTimeout(fxTimer);if(fxCleanup){fxCleanup();fxCleanup=null;}$('#fxVisual').replaceChildren();$('#fxTitle').replaceChildren();$('#fxHost').hidden=true;document.body.style.overflow='';window.__special.activeEffect=null;}
function start(word,id){stop();$('#fxHost').hidden=false;$('#fxTitle').append(make('div','',word),make('small','','FENHAO LIVE · 试播效果'));document.body.style.overflow='hidden';window.__special.activeEffect=id;fxTimer=setTimeout(stop,6500);}
function confettiRun(key){if(!window.confetti)throw new Error('礼炮引擎未加载');const canvas=make('canvas');$('#fxVisual').append(canvas);const cannon=confetti.create(canvas,{resize:true,useWorker:false});const cs=['#dafa83','#bb9eff','#ffb295','#acd2ff','#fff1b8'];const end=performance.now()+3700;let timer;let shape;
if(key==='heart')shape=confetti.shapeFromPath({path:'M 0 10 C -20 -6 -13 -18 0 -7 C 13 -18 20 -6 0 10 Z'});
const fire=()=>{if(performance.now()>end)return;const base={particleCount:18,spread:65,startVelocity:45,colors:cs,ticks:210,disableForReducedMotion:true};if(key==='cannon'){cannon({...base,angle:62,origin:{x:0,y:.75}});cannon({...base,angle:118,origin:{x:1,y:.75}});}else if(key==='gold'){cannon({...base,particleCount:12,startVelocity:2,spread:180,gravity:.55,drift:.1,colors:['#ffe6a0','#dab573','#fff1c2'],origin:{x:Math.random(),y:-.1}});}else if(key==='heart'){cannon({...base,particleCount:26,shapes:[shape],scalar:2.2,startVelocity:35,spread:360,colors:['#ff8fba','#ff508e','#ffc0d6'],origin:{x:.5,y:.5}});}else{cannon({...base,particleCount:28,shapes:['star'],scalar:1.5,spread:100,colors:['#fff2a4','#dafa83','#d6b9ff'],origin:{x:Math.random()*.6+.2,y:.85}});}timer=setTimeout(fire,key==='heart'?550:180);};fire();return()=>{clearTimeout(timer);cannon.reset();};}
function canvasScene(key){const canvas=make('canvas');$('#fxVisual').append(canvas);const ctx=canvas.getContext('2d');const w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);let raf=0;const begin=performance.now();const stars=Array.from({length:100},(_,i)=>({a:i*2.39996,r:(i*97)%Math.max(w,h),speed:1+i%7}));function draw(t){const sec=(t-begin)/1000;ctx.clearRect(0,0,w,h);if(key==='warp'){for(const s of stars){s.r+=s.speed*2;const max=Math.hypot(w,h)*.55;if(s.r>max)s.r=5;const x=Math.cos(s.a),y=Math.sin(s.a),len=s.r*.12;ctx.strokeStyle='rgba(202,184,255,'+Math.min(1,s.r/max+.15)+')';ctx.lineWidth=1+s.r/max;ctx.beginPath();ctx.moveTo(w/2+x*s.r,h/2+y*s.r);ctx.lineTo(w/2+x*(s.r+len),h/2+y*(s.r+len));ctx.stroke();}}else{for(let i=0;i<5;i++){const phase=(sec*.45+i*.2)%1;ctx.strokeStyle='rgba(191,174,255,'+((1-phase)*.5)+')';ctx.lineWidth=2+(1-phase)*5;ctx.beginPath();ctx.arc(w/2,h*.45,20+phase*Math.hypot(w,h)*.6,0,Math.PI*2);ctx.stroke();}const grad=ctx.createRadialGradient(w/2,h*.45,0,w/2,h*.45,w*.45);grad.addColorStop(0,'#8766ef45');grad.addColorStop(1,'#8766ef00');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);}raf=requestAnimationFrame(draw);}raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf);}
function playEffect(a){start(a.word,a.id);try{if(['cannon','gold','heart','stars'].includes(a.key))fxCleanup=confettiRun(a.key);else if(a.key==='fireworks'){const F=window.Fireworks?.default||window.Fireworks?.Fireworks;if(!F)throw new Error('烟花引擎未加载');const fw=new F($('#fxVisual'),{autoresize:true,opacity:.45,acceleration:1.04,friction:.98,gravity:1.15,particles:60,traceLength:3,traceSpeed:8,explosion:5,intensity:28,flickering:0,sound:{enabled:false},hue:{min:20,max:280}});fw.start();fxCleanup=()=>{fw.stop();fw.clear();};}else if(a.key==='parade'){const cleanup=confettiRun('cannon');const bird=byId.get('parrot-0');if(bird)for(let i=0;i<5;i++){const im=image(bird,'dancer');im.style.left=(-i*150)+'px';im.style.animationDelay=(i*.18)+'s';$('#fxVisual').append(im);}fxCleanup=cleanup;}else fxCleanup=canvasScene(a.key);}catch(err){stop();toast(err.message);}}
function playHero(a){start('',a.id);$('#fxTitle').style.top='75%';$('#fxTitle').replaceChildren(make('div','',a.caption||a.name));const el=make('div','giant');$('#fxVisual').append(el);const anims=[];if(a.kind==='answer')playLottie(el,a,anims);else{const im=image(a);im.style.cssText='width:100%;height:100%;object-fit:contain';el.append(im);}const clean=confettiRun('stars');fxCleanup=()=>{clean();dispose(anims);$('#fxTitle').style.top='';};}
function showDetail(a){dispose(detailAnims);$('#detailTitle').textContent=a.name;const body=$('#detailBody');body.replaceChildren();const p=make('div','detail-preview');if(a.kind==='sticker')p.append(image(a));else if(a.kind==='answer'){const n=make('div','answer-art');p.append(n);queueMicrotask(()=>playLottie(n,a,detailAnims));}else p.append(make('strong','',a.glyph));body.append(p);let info=`编号：${a.id}\n格式：${a.format}\n许可：${a.license}`;if(a.kind==='sticker')info+=`\n尺寸：${a.width} × ${a.height} · ${a.frames} 帧 · ${Math.round(a.bytes/1024)} KB\n已从上游动画转换为 WebP，原生大小未增加。`;else if(a.kind==='answer')info+='\n本页新制作的矢量答题牌，不是声称在 GitHub 找到的现成套装。';else info+=`\n引擎：${a.engine}\n这是网页编排，不是一个可单独拖入聊天的 Lottie 文件。`;const text=make('p','meta',info);text.style.whiteSpace='pre-line';body.append(text);const actions=make('div','detail-actions');const sendBtn=make('button','','试播');sendBtn.onclick=()=>{$('#detail').close();send(a);};actions.append(sendBtn);if(a.kind==='sticker'){const link=make('a','','下载 WebP');link.href=a.src;link.download=a.id+'.webp';actions.append(link);}if(a.kind==='answer'){const dl=make('button','','下载 Lottie JSON');dl.onclick=()=>download(a.id+'.json',lottieFor(a));actions.append(dl);const link=make('a','','下载 WebP');link.href='answers/'+a.id+'.webp';link.download=a.id+'.webp';actions.append(link);}const src=make('a','','来源与代码 ↗');src.href=a.kind==='answer'?'https://github.com/muzi2023/jiaozichaxun/tree/main/emoji-special':a.source;src.target='_blank';src.rel='noopener';actions.append(src);body.append(actions);if(a.group==='parrot')body.append(make('p','license-note','小鸟是复古鬼畜风格，并非高清 3D。原仓库素材授权混合，收藏不代表商用授权。'));$('#detail').showModal();}
function showAbout(){dispose(detailAnims);$('#detailTitle').textContent='来源透明，挑选放心';const b=$('#detailBody');b.replaceChildren();const defs=[['Microsoft Fluent Animated','12 个夸张反应。上游为 256px APNG，本页转为 WebP，保留 MIT 声明；中文名字是为课堂试播加的标签。','https://github.com/microsoft/fluentui-emoji-animated'],['Party Parrot','8 个鬼畜小鸟。优先选取仓库的 hd 文件，但这种素材本身是复古线条风格。授权混合，正式商用需核对具体作品。','https://github.com/jmhobbs/cultofthepartyparrot.com'],['canvas-confetti / fireworks-js','本地保存固定版本，分别用来做礼炮与烟花。穿梭和冲击圆环为本页原创 Canvas 编排。','https://github.com/catdad/canvas-confetti'],['ABCD 三套答题牌','本页新制作的轻量矢量 Lottie，字体已转为线条结构，不依赖外部字体。各有 ABCD，并提供 WebP 副本。','https://github.com/muzi2023/jiaozichaxun/tree/main/emoji-special']];for(const [title,desc,url] of defs){const d=make('div','source-block');d.append(make('h3','',title),make('p','',desc));const a=make('a','','打开来源 ↗');a.href=url;a.target='_blank';a.rel='noopener';d.append(a);b.append(d);}$('#detail').showModal();}
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;filter='all';document.querySelectorAll('#tabs [data-tab]').forEach(n=>n.classList.toggle('on',n===b));render();};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(n=>n.classList.toggle('on',n===b));});
$('#compose').onsubmit=e=>{e.preventDefault();const text=$('#textInput').value.trim();if(!text)return;const row=make('div','message');row.append(make('span','','我'),make('div','',text));$('#chat').append(row);$('#textInput').value='';$('#chat').scrollTop=$('#chat').scrollHeight;};
$('#clearChat').onclick=()=>{dispose(chatAnims);$('#chat').replaceChildren();messages=0;$('#messageCount').textContent='0';};$('#mobileChat').onclick=()=>document.body.classList.add('chat-open');$('#closeChat').onclick=()=>document.body.classList.remove('chat-open');$('#stopFx').onclick=stop;document.addEventListener('keydown',e=>{if(e.key==='Escape'){stop();document.body.classList.remove('chat-open');}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});$('#closeDetail').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>dispose(detailAnims));$('#about').onclick=showAbout;
$('#export').onclick=()=>{if(!favorites.size){toast('先收藏几个喜欢的素材');return;}const selection=[...favorites].map(id=>{const a=byId.get(id);return{...a,src:a.kind==='answer'?new URL('answers/'+a.id+'.webp',location.href).href:a.src?new URL(a.src,location.href).href:undefined,animationData:a.kind==='answer'?lottieFor(a):undefined,fullscreenConfig:a.kind==='effect'?{key:a.key,engine:a.engine,maxDurationMs:6500}:undefined};});download('分号-有戏表情精选.json',{version:VERSION,selectedAt:new Date().toISOString(),items:selection});};
window.__special={version:VERSION,count:catalog.length,assets:assets.length,answers:answers.length,effects:effects.length,activeEffect:null};window.SpecialLab={catalog,answers,lottieFor,playEffect,stop,showDetail};save();render();if(!assets.length)$('#health').textContent='素材清单未载入：答题牌和特效仍可试玩，请刷新重试。';
})();
